---
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    pull_policy: always
    ports:
      - 80:80
      - 30020:81
      - 443:443
    environment:
      - DB_MYSQL_HOST=nginxproxymanager-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm
      - DB_MYSQL_NAME=npm
    volumes:
      - ${VOLUME_BASE_PATH}/nginx-proxy-manager/data:/data
      - ${VOLUME_BASE_PATH}/nginx-proxy-manager/ssl:/etc/letsencrypt
  nginxproxymanager-db:
    image: jc21/mariadb-aria:latest
    environment:
      - MYSQL_ROOT_PASSWORD=npm
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm
    volumes:
      - ${VOLUME_BASE_PATH}/nginx-proxy-manager/db:/var/lib/mysql

volumes:
  nginxproxymanager-data:
  nginxproxymanager-ssl:
  nginxproxymanager-db:
