services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    pull_policy: always
    restart: unless-stopped
    ports:
      - 30078:5678
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host(`n8n.nezdemkovski.cloud`) || Host(`n8n.helios.home.nezdemkovski.cloud`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=cloudflare
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    environment:
      - N8N_HOST=n8n.nezdemkovski.cloud
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.nezdemkovski.cloud/
      - GENERIC_TIMEZONE=Europe/Prague
    volumes:
      - ${VOLUME_BASE_PATH}/n8n:/home/node/.n8n
      - ${VOLUME_BASE_PATH}/n8n:/files
networks:
  traefik-proxy:
    external: true