---
services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Prague
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ${VOLUME_BASE_PATH}/bind9/config:/etc/bind
      - ${VOLUME_BASE_PATH}/bind9/cache:/var/cache/bind
      - ${VOLUME_BASE_PATH}/bind9/records:/var/lib/bind
    restart: unless-stopped
    