---
services:
  homer:
    image: "b4bz/homer:latest"
    container_name: homer
    pull_policy: always
    ports:
      - "30010:8080"
    networks:
      - traefik-proxy
    volumes:
      - ${VOLUME_BASE_PATH}/homer/assets/:/www/assets
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host(`nezdemkovski.cloud`) || Host(`helios.home.nezdemkovski.cloud`)
      - traefik.http.routers.homer.entrypoints=websecure
      - traefik.http.routers.homer.tls=true
      - traefik.http.routers.homer.tls.certresolver=cloudflare
      - traefik.http.services.homer.loadbalancer.server.port=3001
networks:
  traefik-proxy:
    external: true
