---
services:
  homer:
    image: "b4bz/homer:latest"
    container_name: homer
    pull_policy: always
    ports:
      - "30010:8080"
    networks:
      - proxy
    volumes:
      - ${VOLUME_BASE_PATH}/homer/assets/:/www/assets
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # Internet Domain Configuration
      - traefik.http.routers.homer-external.rule=Host(`nezdemkovski.cloud`) && PathPrefix(`/`)
      - traefik.http.routers.homer-external.entrypoints=websecure
      - traefik.http.routers.homer-external.tls=true
      - traefik.http.routers.homer-external.tls.certresolver=cloudflare
      # Local Network Domain Configuration
      - traefik.http.routers.homer-internal.rule=Host(`home.lab`) && PathPrefix(`/`)
      - traefik.http.routers.homer-internal.entrypoints=websecure
      - traefik.http.routers.homer-internal.tls=true
      # Common Service Configuration
      - traefik.http.services.homer.loadbalancer.server.port=3001
networks:
  proxy:
    external: true
