---
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:1"
    container_name: uptime-kuma
    pull_policy: always
    restart: unless-stopped
    ports:
      - 30015:3001
    networks:
      - proxy
    volumes:
      - ${VOLUME_BASE_PATH}/uptime-kuma:/app/data
    labels:
      - traefik.enable=true
      # Internet Domain Configuration
      - traefik.http.routers.uptime-kuma-external.rule=Host(`uptime-kuma.nezdemkovski.cloud`) && PathPrefix(`/`)
      - traefik.http.routers.uptime-kuma-external.entrypoints=websecure
      - traefik.http.routers.uptime-kuma-external.tls=true
      - traefik.http.routers.uptime-kuma-external.tls.certresolver=cloudflare
      # Local Network Domain Configuration
      - traefik.http.routers.uptime-kuma-internal.rule=Host(`uptime-kuma.home.lab`) && PathPrefix(`/`)
      - traefik.http.routers.uptime-kuma-internal.entrypoints=websecure
      - traefik.http.routers.uptime-kuma-internal.tls=true
      # Common Service Configuration
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
networks:
  proxy:
    external: true