---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - traefik-proxy
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    volumes:
      - ${VOLUME_BASE_PATH}/cloudflared:/etc/cloudflared
networks:
  traefik-proxy:
    external: true
