---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    volumes:
      - ${VOLUME_BASE_PATH}/cloudflared:/etc/cloudflared
networks:
  default:
    external:
      name: proxy 